#!/usr/bin/env node
/**
 * build-index.js
 *
 * Generates INDEX.md at the repo root from src/articles/**\/*.md frontmatter.
 * INDEX.md is the agent-facing catalog of the corpus: one line per cairn,
 * grep-friendly, ordered newest-first. The agent consults it before drafting
 * a new cairn (to find existing coverage) and before cross-linking.
 *
 * Human-facing browsing lives at /library/, /archives/, /trails/, and tag
 * pages. INDEX.md is a separate surface tuned for the agent's workflow.
 *
 * Re-run on demand:  node scripts/build-index.js
 * Runs automatically as part of `npm run prebuild`.
 */

'use strict';

const fs = require('fs');
const path = require('path');

const REPO_ROOT = path.join(__dirname, '..');
const ARTICLES_ROOT = path.join(REPO_ROOT, 'src', 'articles');
const INDEX_PATH = path.join(REPO_ROOT, 'INDEX.md');

function* walkMarkdown(dir) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) yield* walkMarkdown(full);
    else if (entry.isFile() && entry.name.endsWith('.md')) yield full;
  }
}

function parseFrontmatter(source) {
  const m = source.match(/^---\n([\s\S]*?)\n---\n/);
  if (!m) return {};
  const fm = {};
  const lines = m[1].split('\n');
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const kv = line.match(/^([a-zA-Z_]+):\s*(.*)$/);
    if (!kv) continue;
    const [, key, valRaw] = kv;
    const val = valRaw.trim();
    if (val === '') {
      // bare key — could be a block scalar (key: |, key: >, key:) or a block
      // sequence (key:\n  - item). Peek ahead. Only block sequences are
      // promoted to an inline `[a, b]` form; block scalars are ignored.
      const items = [];
      let j = i + 1;
      while (j < lines.length && /^\s+-\s+/.test(lines[j])) {
        items.push(lines[j].replace(/^\s+-\s+/, '').trim());
        j++;
      }
      if (items.length > 0) {
        fm[key] = `[${items.join(', ')}]`;
        i = j - 1;
      }
    } else {
      fm[key] = val;
    }
  }
  return fm;
}

function stripQuotes(s) {
  if (!s) return '';
  return s.replace(/^["']|["']$/g, '');
}

function parseTags(raw) {
  if (!raw) return [];
  const inner = raw.replace(/^\[|\]$/g, '').trim();
  if (!inner) return [];
  return inner.split(',').map((t) => stripQuotes(t.trim())).filter(Boolean);
}

// Undated filenames (e.g. `the-quiet-teammate.md`) are supported by design —
// the regex matches only when a `YYYY-MM-DD-` prefix is present and strips it.
function slugFromFilename(filePath) {
  const base = path.basename(filePath, '.md');
  return base.replace(/^\d{4}-\d{2}-\d{2}-/, '');
}

function loadCairns() {
  const cairns = [];
  for (const file of walkMarkdown(ARTICLES_ROOT)) {
    const source = fs.readFileSync(file, 'utf-8');
    const fm = parseFrontmatter(source);
    if (!fm.title) continue;
    if (fm.status && stripQuotes(fm.status) === 'draft') continue;
    cairns.push({
      slug: slugFromFilename(file),
      file: path.relative(REPO_ROOT, file),
      title: stripQuotes(fm.title),
      subtitle: stripQuotes(fm.subtitle),
      date: fm.date || '',
      duration: parseInt(fm.duration || '0', 10) || null,
      tags: parseTags(fm.tags),
      trail: stripQuotes(fm.trail || ''),
      trailOrder: fm.trailOrder ? parseInt(fm.trailOrder, 10) : null,
      featured: stripQuotes(fm.featured || '') === 'true',
    });
  }
  cairns.sort((a, b) => (a.date < b.date ? 1 : a.date > b.date ? -1 : 0));
  return cairns;
}

function renderCairnLine(c) {
  const parts = [`\`${c.slug}\``, c.date || '?'];
  if (c.duration) parts.push(`${c.duration}min`);
  if (c.trail) parts.push(`trail:${c.trail}[${c.trailOrder ?? '?'}]`);
  if (c.featured) parts.push('featured');
  if (c.tags.length) parts.push(`tags:${c.tags.join(',')}`);
  const meta = parts.join(' · ');
  const blurb = c.subtitle ? ` — ${c.subtitle}` : '';
  return `- ${meta}\n  **${c.title}**${blurb}`;
}

function buildTrails(cairns) {
  const byTrail = new Map();
  for (const c of cairns) {
    if (!c.trail) continue;
    if (!byTrail.has(c.trail)) byTrail.set(c.trail, []);
    byTrail.get(c.trail).push(c);
  }
  for (const arr of byTrail.values()) {
    arr.sort((a, b) => (a.trailOrder || 0) - (b.trailOrder || 0));
  }
  return byTrail;
}

function render(cairns) {
  const trails = buildTrails(cairns);
  const lines = [];
  lines.push('# Cairns Index');
  lines.push('');
  lines.push('> Auto-generated by `scripts/build-index.js` (runs as part of `npm run prebuild`).');
  lines.push('> Do not edit by hand — changes will be overwritten. Edit the source cairns instead.');
  lines.push('>');
  lines.push('> The agent reads this file first when surveying the corpus: before drafting,');
  lines.push('> cross-linking, or answering questions about what is already published.');
  lines.push('> For human-facing browsing see `/library/`, `/archives/`, `/trails/`, and tag pages.');
  lines.push('');
  const cn = cairns.length === 1 ? 'cairn' : 'cairns';
  const tn = trails.size === 1 ? 'trail' : 'trails';
  lines.push(`_${cairns.length} ${cn} · ${trails.size} ${tn}_`);
  lines.push('');

  lines.push('## Trails');
  lines.push('');
  if (trails.size === 0) {
    lines.push('_None._');
  } else {
    const sortedTrails = [...trails.entries()].sort((a, b) => {
      const maxA = a[1].reduce((m, c) => (c.date > m ? c.date : m), '');
      const maxB = b[1].reduce((m, c) => (c.date > m ? c.date : m), '');
      return maxB.localeCompare(maxA);
    });
    for (const [name, parts] of sortedTrails) {
      lines.push(`- **${name}** (${parts.length} parts) — ${parts.map((p) => `\`${p.slug}\``).join(' → ')}`);
    }
  }
  lines.push('');

  lines.push('## Cairns (newest first)');
  lines.push('');
  for (const c of cairns) {
    lines.push(renderCairnLine(c));
  }
  lines.push('');
  return lines.join('\n');
}

function main() {
  if (!fs.existsSync(ARTICLES_ROOT)) {
    console.error(`articles root not found: ${ARTICLES_ROOT}`);
    process.exit(2);
  }
  const cairns = loadCairns();
  const out = render(cairns);
  fs.writeFileSync(INDEX_PATH, out);
  console.log(`build-index: wrote INDEX.md (${cairns.length} cairns)`);
}

main();
